version: "3.8"

services:
  runner-0: # change this to runner-1, runner-2, etc.
    build:
      context: ..
      dockerfile: .platform/DOCKERFILE
    shm-size: 2G
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 142g # 1/7 of the total memory in the server
    mem_limit: 142g
    environment:
      - RUNNER_TOKEN=${RUNNER_TOKEN} # Pass GitHub runner token as env variable
      - NVIDIA_VISIBLE_DEVICES=${GPU_ID:-0} # Specify which GPU to use, default to 0
    volumes:
      - ../datasets:/home/user/datasets:ro # Mount datasets as read-only
    entrypoint: >
      /bin/bash -c "
      if [ ! -f /home/user/actions-runner/.credentials ]; then
        ./actions-runner/config.sh --url https://github.com/vanderschaarlab/vand2025 --token $$RUNNER_TOKEN --unattended
      fi
      ./actions-runner/run.sh
      "
