[project]
name = "merge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pandas"]

[project.scripts]
merge = "merge.main:main"